# Description: script to import mssql image from docker hub then copies backup database file and sql script \ 
#              from the same dirctory to docker image then execute the script which will restore the database
# Author: Lotfy Ashmawy  

FROM mcr.microsoft.com/mssql/server:2019-latest
ENV MSSQL_PID=Developer
ENV SA_PASSWORD=lotfy_123
ENV ACCEPT_EULA=Y

USER mssql
COPY Install_backup.sql /var/opt/mssql/
COPY WideWorldImporters-Standard.bak var/opt/mssql/backup/
RUN ( /opt/mssql/bin/sqlservr & ) | grep -q "Service Broker manager has started" \
    && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P lotfy_123 -i /var/opt/mssql/Install_backup.sql -C \ 
    && pkill sqlservr

CMD ["opt/mssql/bin/sqlservr"]
